version: '3.4'

services:
  docker-prune:
    container_name: docker_gc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SLEEP: '30m'       # prune every 30m
      AGE: '48h'         # prune older than 48h
      STICKY_LABEL: 'permanent=true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global      # run on every docker node

